name: Snyk Scan
on:
  push:
    branches:
       - 'feature/*'
       - 'main'

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Setup Snyk CLI
        run: |-
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/ 
     
      - name: Auth Secrets for Snyk Cli
        run: |
          echo "SNYK_TOKEN="`echo ${{ secrets.SNYK_TOKEN }}`"" >> $GITHUB_ENV
          echo "SNYK_ORGANIZATION_ID="`echo ${{ secrets.SNYK_ORGANIZATION_ID }}`"" >> $GITHUB_ENV
          snyk config set org=${{ secrets.SNYK_ORGANIZATION_ID }}

      - name: Run Snyk Scan
        run: 
          snyk test --all-projects --severity-threshold=high
