name: Snyk Scan
on:
  push:
    branches:
       - 'feature/*'
       - 'main'

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: [ubuntu-latest]
    steps:
  #Snyk for JAVA MS
      # - name: Checkout branch ${{ github.ref }}
      #   uses: actions/checkout@v3
      # - name: Setup Snyk CLI
      #   run: |-
      #     curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
      #     chmod +x ./snyk
      #     mv ./snyk /usr/local/bin/ 
     
      # - name: Auth Secrets for Snyk Cli
      #   run: |
      #     echo "SNYK_TOKEN="`echo ${{ secrets.SNYK_TOKEN }}`"" >> $GITHUB_ENV
      #     echo "SNYK_ORGANIZATION_ID="`echo ${{ secrets.SNYK_ORGANIZATION_ID }}`"" >> $GITHUB_ENV
      
      # - name: Run Snyk Scan
      #   run: 
      #     snyk code test --all-project --severity-threshold=high

#Snyk for Python
      - name: Checkout code
        uses: actions/checkout@master

      - name: Snyk Scan for Python Project
        uses: snyk/actions/python@master
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

        