name: Snyk Scan
on:
  push:
    branches:
       - 'feature/*'
       - 'main'

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Setup Snyk CLI
        run: |-
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/ 
     
      - name: Auth Secrets for Snyk Cli
        run: |
          echo "SNYK_TOKEN="`echo ${{ secrets.SNYK_TOKEN }}`"" >> $GITHUB_ENV
          echo "SNYK_ORGANIZATION_ID="`echo ${{ secrets.SNYK_ORGANIZATION_ID }}`"" >> $GITHUB_ENV
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
           python-version: "3.10"
           architecture: "x64"

      - name: Run Snyk Scan
        run: |-
          cd src/
          pip install -r requirements.txt
          snyk test --file=requirements.txt --severity-threshold=high --org=a34afe19-31e7-424e-a587-a85198bf886b